# .github/workflows/netlify.yml
name: Automatically Generate Comment
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v2      
=======
      - uses: actions/checkout@v2
>>>>>>> 9d7f144863566b1abcc1c03c86b30f2889258cf3
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://noaether-cdn.netlify.app/.netlify/functions/gitComment'
          method: 'POST'
          data: '{ "commitId": "${{ github.sha }}", "GITHUB_REPOSITORY": "noaether/nemail-client", "GITHUB_TOKEN": "${{ secrets.GH_TOKEN }}", "API_KEY": "${{ secrets.API_KEY }}" }'
