name: Workflow for Codecov example-java-maven
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Install dependencies
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B
      - name: Run tests and collect coverage
        run: mvn clean validate test --no-build-cache -B
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
