name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  checks: write
  pull-requests: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v1.4.4
      with:
        java-version: '17'
    - name: Build with Maven
      run: mvn -B clean package test --file pom.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      id: test-results
      if: always()
      with:
        files: |
          target/surefire-reports/**/*.xml

    - name: Set badge color
      shell: bash
      run: |
        case ${{ fromJSON( steps.test-results.outputs.json ).conclusion }} in
          success)
            echo "BADGE_COLOR=31c653" >> $GITHUB_ENV
            ;;
          failure)
            echo "BADGE_COLOR=800000" >> $GITHUB_ENV
            ;;
          neutral)
            echo "BADGE_COLOR=696969" >> $GITHUB_ENV
            ;;
        esac

    - name: wget
      uses: wei/wget@v1
      with:
        args: https://img.shields.io/static/v1?label=TESTS&message=${{ fromJSON( steps.test-results.outputs.json ).stats.tests_succ }}%20%E2%9C%94%20%7C%20${{ fromJSON( steps.test-results.outputs.json ).stats.tests_skip }}%20%E2%9E%A6%20%7C%20%${{ fromJSON( steps.test-results.outputs.json ).stats.tests_fail }}%20%E2%9C%97&color=f2993a

    - name: Upload badge to Gist
      # Upload only for master branch
      if: >
        github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'main' ||
        github.event_name != 'workflow_run' && github.ref == 'refs/heads/main'
      uses: andymckay/append-gist-action@1fbfbbce708a39bd45846f0955ed5521f2099c6d
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gistURL: https://gist.githubusercontent.com/noaether/97da96712e6943076ea2213ed504009c
        file: v1.svg

  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v1.4.4
      with:
        java-version: '17'
    - name: Build with Maven
      run: mvn -B clean verify --file pom.xml
