name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v1.4.4
      with:
        java-version: '17'
    - name: Build with Maven
      run: mvn -B clean package test --file pom.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v1.4.4
      with:
        java-version: '17'
    - name: Build with Maven
      run: mvn -B clean verify --file pom.xml
