name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  checks: write
  pull-requests: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v1.4.4
      with:
        java-version: '17'
    - name: Build with Maven
      run: mvn -B clean package test --file pom.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          target/surefire-reports/**/*.xml
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v1.4.4
      with:
        java-version: '17'
    - name: Build with Maven
      run: mvn -B clean verify --file pom.xml
